import { createCipheriv, createHash, randomBytes } from "node:crypto";
import { NextRequest, NextResponse } from "next/server";
export const runtime = "nodejs";
export const dynamic = "force-dynamic";
const txt=(v:unknown,m:number)=>typeof v==="string"?v.trim().slice(0,m):"";
const num=(v:unknown,f:number,m:number)=>Number.isFinite(Number(v))?Math.max(0,Math.min(Math.trunc(Number(v)),m)):f;
function key(){const s=process.env.INSTAGRAM_CREDENTIAL_ENCRYPTION_KEY?.trim();if(!s||s.length<32)throw new Error("인스타 로그인 암호화 키가 설정되지 않았습니다.");return createHash("sha256").update(s).digest();}
function encrypt(p:string){const iv=randomBytes(12);const c=createCipheriv("aes-256-gcm",key(),iv);const out=Buffer.concat([c.update(p,"utf8"),c.final()]);return{ciphertext:out.toString("base64"),iv:iv.toString("base64"),tag:c.getAuthTag().toString("base64")};}
export async function POST(req:NextRequest){try{const url=process.env.NEXT_PUBLIC_SUPABASE_URL,anon=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,service=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!anon||!service)return NextResponse.json({error:"서버 환경변수가 설정되지 않았습니다."},{status:500});const auth=req.headers.get("authorization")||"",token=auth.startsWith("Bearer ")?auth.slice(7):"";if(!token)return NextResponse.json({error:"로그인이 필요합니다."},{status:401});const ur=await fetch(`${url}/auth/v1/user`,{headers:{apikey:anon,Authorization:`Bearer ${token}`},cache:"no-store"});if(!ur.ok)return NextResponse.json({error:"로그인 정보가 만료되었습니다."},{status:401});const user=await ur.json() as {id?:string};if(!user.id)return NextResponse.json({error:"회원 정보를 확인하지 못했습니다."},{status:401});const b=await req.json() as Record<string,unknown>;const username=txt(b.instagramUsername,100).replace(/^@/,""),password=typeof b.instagramPassword==="string"?b.instagramPassword:"";if(!username)return NextResponse.json({error:"인스타그램 아이디를 입력해 주세요."},{status:400});if(password.length<4||password.length>200)return NextResponse.json({error:"인스타그램 비밀번호를 정확히 입력해 주세요."},{status:400});const e=encrypt(password);const rr=await fetch(`${url}/rest/v1/rpc/create_instagram_optimization_order_secure`,{method:"POST",headers:{apikey:service,Authorization:`Bearer ${service}`,"Content-Type":"application/json"},body:JSON.stringify({p_user_id:user.id,p_instagram_username:username,p_password_ciphertext:e.ciphertext,p_password_iv:e.iv,p_password_tag:e.tag,p_follow_enabled:Boolean(b.followEnabled),p_follow_keywords:txt(b.followKeywords,500),p_feed_follow_limit:num(b.feedFollowLimit,10,500),p_search_follow_limit:num(b.searchFollowLimit,10,500),p_like_enabled:Boolean(b.likeEnabled),p_like_keywords:txt(b.likeKeywords,500),p_feed_like_limit:num(b.feedLikeLimit,25,1000),p_search_like_limit:num(b.searchLikeLimit,25,1000),p_story_enabled:Boolean(b.storyEnabled),p_story_daily_limit:num(b.storyDailyLimit,30,1000),p_comment_enabled:Boolean(b.commentEnabled),p_comment_daily_limit:num(b.commentDailyLimit,5,100),p_comment_templates:txt(b.commentTemplates,5000)})});const data=await rr.json().catch(()=>null) as {message?:string}|number|null;if(!rr.ok)return NextResponse.json({error:data&&typeof data==="object"&&"message" in data?String(data.message):"인스타 계정 신청 중 오류가 발생했습니다."},{status:400});return NextResponse.json({ok:true,orderId:data});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"인스타 계정 신청 중 오류가 발생했습니다."},{status:500});}}
