create table if not exists public.place_analysis_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  place_id text not null,
  keyword text not null,
  client_name text,
  place_name text,
  my_rank integer,
  visitor_review_count integer,
  blog_review_count integer,
  search_total integer,
  report_url text,
  result_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists place_analysis_history_user_created_idx on public.place_analysis_history(user_id, created_at desc);
alter table public.place_analysis_history enable row level security;
drop policy if exists "Users can view own place analyses" on public.place_analysis_history;
create policy "Users can view own place analyses" on public.place_analysis_history for select using (auth.uid() = user_id or public.is_admin());
grant select on public.place_analysis_history to authenticated;
grant usage, select on sequence public.place_analysis_history_id_seq to authenticated;
