"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, Bot, CheckCircle2, Clipboard, Coins, Download, ImagePlus, Images, Loader2, RotateCcw, Sparkles, Trash2, UploadCloud, WalletCards } from "lucide-react";
import { getSupabaseBrowserClient } from "@/lib/supabase";
import { getPointBalance } from "@/lib/points";

type History={id:number;main_keyword:string;body:string;char_count:number;point_cost:number;created_at:string;image_names:string[]|null};
type Generated={body:string;char_count:number;retry_count:number;reached_target:boolean;balance:number;cost:number;elapsed_ms:number;image_names:string[]};
type SelectedImage={id:string;file:File;preview:string};
const toneOptions=[{value:"haeyo",label:"했어요체"},{value:"hapnida",label:"합니다체"},{value:"hada",label:"했다체"},{value:"mix",label:"혼합체"}];

async function compressImage(file:File):Promise<File>{
  if(!file.type.startsWith("image/"))throw new Error(`${file.name}은 이미지 파일이 아닙니다.`);
  const bitmap=await createImageBitmap(file);const max=1600;const scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height));
  const canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));
  const ctx=canvas.getContext("2d");if(!ctx)throw new Error("이미지를 처리하지 못했습니다.");ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();
  const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,"image/jpeg",.78));if(!blob)throw new Error("이미지 압축에 실패했습니다.");
  const base=file.name.replace(/\.[^.]+$/,"" ).replace(/[^a-zA-Z0-9가-힣_-]/g,"_");return new File([blob],`${base}.jpg`,{type:"image/jpeg"});
}

export default function BlogAiImagesPage(){
  const router=useRouter();const[loading,setLoading]=useState(true);const[generating,setGenerating]=useState(false);const[balance,setBalance]=useState(0);const[history,setHistory]=useState<History[]>([]);
  const[images,setImages]=useState<SelectedImage[]>([]);const[mainKeyword,setMainKeyword]=useState("");const[subKeyword,setSubKeyword]=useState("");const[mainRepeat,setMainRepeat]=useState(6);const[targetChars,setTargetChars]=useState(2000);const[paragraphCount,setParagraphCount]=useState(7);const[tone,setTone]=useState("haeyo");const[style,setStyle]=useState("narrative");const[guide,setGuide]=useState("");
  const[status,setStatus]=useState("");const[elapsed,setElapsed]=useState(0);const[error,setError]=useState("");const[result,setResult]=useState<Generated|null>(null);const[copied,setCopied]=useState(false);const[processing,setProcessing]=useState(false);
  const canGenerate=balance>=1000&&mainKeyword.trim().length>0&&images.length>0&&!generating&&!processing;
  useEffect(()=>{const s=getSupabaseBrowserClient();if(!s){setLoading(false);return;}void(async()=>{const{data}=await s.auth.getUser();if(!data.user){router.replace("/");return;}await s.rpc("ensure_my_profile");try{setBalance(await getPointBalance(s,data.user.id));}catch{}const{data:h}=await s.from("blog_ai_generations").select("id,main_keyword,body,char_count,point_cost,created_at,image_names").eq("user_id",data.user.id).eq("generation_type","image").order("created_at",{ascending:false}).limit(8);setHistory((h??[]) as History[]);setLoading(false);})();return()=>images.forEach(i=>URL.revokeObjectURL(i.preview));},[router]);
  const totalSize=useMemo(()=>images.reduce((s,i)=>s+i.file.size,0),[images]);
  async function addFiles(list:FileList|null){if(!list)return;setProcessing(true);setError("");try{const remain=12-images.length;const chosen=Array.from(list).slice(0,remain);const compressed=await Promise.all(chosen.map(compressImage));const next=compressed.map(file=>({id:crypto.randomUUID(),file,preview:URL.createObjectURL(file)}));setImages(prev=>[...prev,...next]);}catch(e){setError(e instanceof Error?e.message:"이미지를 처리하지 못했습니다.");}finally{setProcessing(false);}}
  function removeImage(id:string){setImages(prev=>{const target=prev.find(i=>i.id===id);if(target)URL.revokeObjectURL(target.preview);return prev.filter(i=>i.id!==id);});}
  async function generate(){if(!canGenerate)return;const s=getSupabaseBrowserClient();if(!s)return;setGenerating(true);setError("");setResult(null);setStatus("이미지 분석 요청을 준비하고 있습니다.");setElapsed(0);try{const{data}=await s.auth.getSession();const token=data.session?.access_token;if(!token)throw new Error("로그인이 필요합니다.");const form=new FormData();form.append("requestId",crypto.randomUUID());form.append("mainKeyword",mainKeyword);form.append("subKeyword",subKeyword);form.append("mainRepeat",String(mainRepeat));form.append("targetChars",String(targetChars));form.append("paragraphCount",String(paragraphCount));form.append("tone",tone);form.append("style",style);form.append("guide",guide);images.forEach(i=>form.append("files",i.file,i.file.name));
    const response=await fetch("/api/blog-ai/generate-with-images",{method:"POST",headers:{Authorization:`Bearer ${token}`},body:form});if(!response.ok||!response.body)throw new Error("이미지 원고 생성 서버에 연결하지 못했습니다.");const reader=response.body.getReader();const decoder=new TextDecoder();let buffer="";while(true){const{done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const chunks=buffer.split("\n\n");buffer=chunks.pop()??"";for(const chunk of chunks){const lines=chunk.split("\n");const eventName=lines.find(l=>l.startsWith("event:"))?.slice(6).trim();const dataLine=lines.find(l=>l.startsWith("data:"))?.slice(5).trim();if(!eventName||!dataLine)continue;const payload=JSON.parse(dataLine);if(eventName==="status"){setStatus(payload.message||"이미지를 분석하고 있습니다.");setElapsed(Number(payload.elapsed||0));}if(eventName==="insufficient"){setBalance(Number(payload.balance||0));throw new Error(payload.message||"보유 포인트가 부족합니다.");}if(eventName==="error")throw new Error(payload.message||"이미지 원고 생성 중 오류가 발생했습니다.");if(eventName==="complete"){setResult(payload as Generated);setBalance(Number(payload.balance||0));setStatus("이미지 분석 원고가 완성되었습니다.");const{data:h}=await s.from("blog_ai_generations").select("id,main_keyword,body,char_count,point_cost,created_at,image_names").eq("generation_type","image").order("created_at",{ascending:false}).limit(8);setHistory((h??[]) as History[]);}}}}
    catch(e){setError(e instanceof Error?e.message:"이미지 원고 생성 중 오류가 발생했습니다.");}finally{setGenerating(false);}}
  async function copyBody(){if(!result)return;await navigator.clipboard.writeText(result.body);setCopied(true);setTimeout(()=>setCopied(false),1600);}
  function downloadBody(){if(!result)return;const blob=new Blob([result.body],{type:"text/plain;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`${mainKeyword||"이미지분석원고"}.txt`;a.click();URL.revokeObjectURL(url);}
  function previewParts(body:string){const marker=/\[([^\]]+?)\s*배치:\s*([^\]]+)\]/g;const parts:Array<{type:"text"|"image";text:string;name?:string;description?:string}>=[];let last=0;let m:RegExpExecArray|null;while((m=marker.exec(body))){if(m.index>last)parts.push({type:"text",text:body.slice(last,m.index)});parts.push({type:"image",text:m[0],name:m[1].trim(),description:m[2].trim()});last=marker.lastIndex;}if(last<body.length)parts.push({type:"text",text:body.slice(last)});return parts;}
  if(loading)return <main className="loading-screen"><Loader2 className="spin" size={32}/><span>이미지 분석 글쓰기 화면을 불러오고 있습니다.</span></main>;
  return <main className="blog-ai-page image-blog-page"><header className="blog-ai-header"><button onClick={()=>router.push("/dashboard")}><ArrowLeft size={19}/>대시보드</button><div className="blog-ai-balance"><WalletCards size={18}/><span>보유 포인트</span><strong>{balance.toLocaleString()}P</strong></div></header>
    <section className="blog-ai-hero image-ai-hero"><span><Images size={15}/> MOSTAD VISION BLOG AI</span><h1>이미지 분석 블로그 글쓰기</h1><p>사진을 분석해 장면과 특징을 원고에 반영하고, 본문 안에 이미지 배치 위치까지 표시합니다.</p><div><Coins size={18}/><strong>원고 1편당 1,000P</strong><em>생성 성공 후에만 차감</em></div></section>
    <div className="blog-ai-layout"><section className="blog-ai-form-card"><div className="blog-ai-section-title"><span>01</span><div><h2>이미지와 원고 조건</h2><p>이미지는 자동 압축되며 최대 12장까지 첨부할 수 있습니다.</p></div></div>
      <label className="image-upload-zone"><input type="file" accept="image/*" multiple onChange={e=>{void addFiles(e.target.files);e.currentTarget.value="";}}/><UploadCloud size={31}/><strong>{processing?"이미지 압축 중...":"이미지를 클릭하거나 끌어다 놓으세요"}</strong><span>JPG·PNG·WEBP · 자동 최적화 · 현재 {(totalSize/1024/1024).toFixed(1)}MB</span></label>
      {images.length>0&&<div className="image-preview-grid">{images.map((image,index)=><article key={image.id}><img src={image.preview} alt={`${index+1}번째 첨부 이미지`}/><span>{index+1}</span><div><strong>{image.file.name}</strong><small>{Math.round(image.file.size/1024)}KB</small></div><button onClick={()=>removeImage(image.id)} aria-label="이미지 삭제"><Trash2 size={15}/></button></article>)}</div>}
      <div className="blog-ai-form-grid"><label><span>메인 키워드 <b>필수</b></span><input value={mainKeyword} onChange={e=>setMainKeyword(e.target.value)} placeholder="예: 홍대 감성카페"/></label><label><span>서브 키워드</span><input value={subKeyword} onChange={e=>setSubKeyword(e.target.value)} placeholder="예: 홍대 데이트, 연남동 카페"/></label></div>
      <div className="blog-ai-range-grid"><label><span>목표 글자수 <strong>{targetChars.toLocaleString()}자</strong></span><input type="range" min="500" max="5000" step="100" value={targetChars} onChange={e=>setTargetChars(Number(e.target.value))}/></label><label><span>문단 수 <strong>{paragraphCount}개</strong></span><input type="range" min="2" max="15" value={paragraphCount} onChange={e=>setParagraphCount(Number(e.target.value))}/></label><label><span>키워드 반복 <strong>{mainRepeat}회</strong></span><input type="range" min="1" max="20" value={mainRepeat} onChange={e=>setMainRepeat(Number(e.target.value))}/></label></div>
      <div className="blog-ai-form-grid"><label><span>어조</span><select value={tone} onChange={e=>setTone(e.target.value)}>{toneOptions.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label><label><span>글 스타일</span><select value={style} onChange={e=>setStyle(e.target.value)}><option value="narrative">서술형</option><option value="quote">인용구 포함</option></select></label></div>
      <label className="blog-ai-guide"><span>추가 가이드</span><textarea value={guide} onChange={e=>setGuide(e.target.value)} placeholder="사진에서 특히 강조할 부분, 업체 특징, 원하는 글의 흐름을 적어 주세요."/></label>
      <div className="blog-ai-order-summary"><div><ImagePlus size={20}/><span>첨부 이미지</span><strong>{images.length}장</strong></div><div><Coins size={20}/><span>차감 포인트</span><strong>1,000P</strong></div></div>
      {balance<1000&&<div className="blog-ai-warning">보유 포인트가 부족합니다.<button onClick={()=>router.push("/points")}>포인트 충전</button></div>}{error&&<div className="blog-ai-error">{error}</div>}
      <button className="blog-ai-generate" disabled={!canGenerate} onClick={generate}>{generating?<><Loader2 className="spin" size={20}/>{status||"이미지 분석 중..."}</>:<><Bot size={20}/>이미지 분석 원고 생성하기</>}</button>{generating&&<div className="blog-ai-progress"><div><i/><i/><i/></div><strong>{status}</strong><span>{elapsed>0?`${elapsed}초 경과 · `:""}최대 3~4분 정도 걸릴 수 있습니다.</span></div>}
    </section><aside className="blog-ai-history"><div className="blog-ai-section-title compact"><span>02</span><div><h2>최근 이미지 원고</h2><p>최근 8개 생성 기록입니다.</p></div></div>{history.length?history.map(h=><button key={h.id} onClick={()=>{setMainKeyword(h.main_keyword);setResult({body:h.body,char_count:h.char_count,retry_count:0,reached_target:true,balance,cost:h.point_cost,elapsed_ms:0,image_names:h.image_names??[]});window.scrollTo({top:0,behavior:"smooth"});}}><div><strong>{h.main_keyword}</strong><span>{new Intl.DateTimeFormat("ko-KR",{dateStyle:"medium"}).format(new Date(h.created_at))}</span></div><small>{h.image_names?.length??0}장 · {h.char_count.toLocaleString()}자</small></button>):<div className="blog-ai-history-empty">아직 생성한 이미지 원고가 없습니다.</div>}</aside></div>
    {result&&<section className="blog-ai-result"><div className="blog-ai-result-head"><div><span><CheckCircle2 size={17}/>이미지 분석 완료</span><h2>{mainKeyword} 원고 미리보기</h2><p>{images.length||result.image_names.length}장의 이미지 · 공백 제외 {result.char_count.toLocaleString()}자</p></div><div><button onClick={copyBody}><Clipboard size={17}/>{copied?"복사 완료":"원고 복사"}</button><button onClick={downloadBody}><Download size={17}/>TXT 저장</button><button onClick={()=>setResult(null)}><RotateCcw size={17}/>새 원고</button></div></div><article className="image-article-preview">{previewParts(result.body).map((part,index)=>{if(part.type==="text")return <div className="blog-ai-output" key={index}>{part.text}</div>;const image=images.find(i=>i.file.name===part.name)||images.find(i=>part.name?.includes(i.file.name.replace(/\.[^.]+$/,"")));return <figure key={index}>{image?<img src={image.preview} alt={part.description}/>:<div className="missing-image"><Images size={28}/><span>{part.name}</span></div>}<figcaption><strong>이미지 배치</strong>{part.description}</figcaption></figure>;})}</article></section>}
  </main>;
}
