"use client";
import {FormEvent,useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {ArrowLeft,Coins,Loader2,Search,Sparkles} from "lucide-react";
import {getSupabaseBrowserClient} from "@/lib/supabase";
import {getPointBalance} from "@/lib/points";
type Stat={keyword:string;volume_pc:number;volume_mobile:number;volume_total:number;doc_count:number|null;ratio:number|null;score:number|null;grade:string|null;competition:string};
type Result={seed:string;seed_found:boolean;seed_stats:Stat|null;recommendations:Stat[];related_count:number;candidate_count:number;analyzed_count:number;hint:string|null};
export default function KeywordAnalysisPage(){const r=useRouter();const[keyword,setKeyword]=useState("");const[balance,setBalance]=useState(0);const[loading,setLoading]=useState(true);const[running,setRunning]=useState(false);const[msg,setMsg]=useState("");const[error,setError]=useState(false);const[result,setResult]=useState<Result|null>(null);
 useEffect(()=>{(async()=>{const s=getSupabaseBrowserClient();if(!s)return;const{data}=await s.auth.getUser();if(!data.user){r.replace("/");return}setBalance(await getPointBalance(s,data.user.id));setLoading(false)})()},[r]);
 async function submit(e:FormEvent){e.preventDefault();if(!keyword.trim()||running)return;setRunning(true);setResult(null);setError(false);setMsg("분석 요청을 준비하고 있습니다.");const s=getSupabaseBrowserClient();const session=(await s?.auth.getSession()).data.session;if(!session){setMsg("로그인이 필요합니다.");setError(true);setRunning(false);return}try{const res=await fetch("/api/keyword-analysis/run",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({seedKeyword:keyword.trim(),requestId:crypto.randomUUID()})});if(!res.body)throw new Error("분석 응답을 받지 못했습니다.");const reader=res.body.getReader(),decoder=new TextDecoder();let buffer="";while(true){const{done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const parts=buffer.split("\n\n");buffer=parts.pop()||"";for(const part of parts){let event="",data="";for(const line of part.split("\n")){if(line.startsWith("event: "))event=line.slice(7);if(line.startsWith("data: "))data+=line.slice(6)}if(!data)continue;const payload=JSON.parse(data);if(event==="status")setMsg(`${payload.message}${payload.elapsed?` (${Math.round(payload.elapsed)}초 경과)`:""}`);if(event==="insufficient"){setMsg("포인트가 부족해 분석할 수 없습니다.");setError(true);setBalance(payload.balance||0)}if(event==="complete"){setResult(payload.result);setBalance(payload.balance);setMsg("분석이 완료되었습니다.")}if(event==="error"){setMsg(payload.message);setError(true)}}}}catch(err){setMsg(err instanceof Error?err.message:"분석 중 오류가 발생했습니다.");setError(true)}finally{setRunning(false)}}
 const s=result?.seed_stats;const num=(v:number|null|undefined)=>v==null?"-":v.toLocaleString();
 return <main className="keyword-page"><div className="keyword-shell"><div className="keyword-topbar"><button onClick={()=>r.push("/dashboard")}><ArrowLeft size={16}/> 대시보드</button></div><section className="keyword-hero"><div><span><Sparkles size={14}/> MOSTAD KEYWORD LAB</span><h1>검색량·경쟁률 분석</h1><p>키워드 검색량과 문서 수를 비교하고 진입하기 좋은 연관 키워드를 찾아보세요.</p></div><div className="keyword-credit"><span>보유 포인트</span><strong>{balance.toLocaleString()}P</strong><small>분석 성공 시 250P 차감</small></div></section><form className="keyword-form" onSubmit={submit}><input value={keyword} onChange={e=>setKeyword(e.target.value)} placeholder="분석할 키워드를 입력하세요. 예: 대전두피문신" maxLength={100}/><button disabled={loading||running||balance<250}>{running?<><Loader2 className="spin" size={17}/> 분석 중</>:<><Search size={17}/> 키워드 분석</>}</button></form>{msg&&<div className={`keyword-message ${error?"error":""}`}>{msg}</div>}
 {s&&<><section className="keyword-summary"><article className="keyword-card"><span>월간 검색량</span><strong>{num(s.volume_total)}</strong><small>PC {num(s.volume_pc)} · 모바일 {num(s.volume_mobile)}</small></article><article className="keyword-card"><span>블로그 문서 수</span><strong>{num(s.doc_count)}</strong><small>네이버 검색 문서 기준</small></article><article className="keyword-card"><span>경쟁률</span><strong>{s.ratio==null?"-":s.ratio.toFixed(3)}</strong><small>문서 수 ÷ 검색량</small></article><article className="keyword-card"><span>등급</span><strong>{s.grade||"-"}</strong><small>경쟁강도 {s.competition||"-"}</small></article><article className="keyword-card"><span>종합 점수</span><strong>{s.score==null?"-":s.score.toFixed(1)}</strong><small>높을수록 진입 유리</small></article></section><section className="keyword-result-panel"><h2>추천 연관 키워드</h2>{result?.recommendations?.length?<table className="keyword-table"><thead><tr><th>키워드</th><th>검색량</th><th>문서 수</th><th>경쟁률</th><th>등급</th><th>점수</th><th/></tr></thead><tbody>{result.recommendations.map(x=><tr key={x.keyword}><td><b>{x.keyword}</b></td><td>{num(x.volume_total)}</td><td>{num(x.doc_count)}</td><td>{x.ratio==null?"-":x.ratio.toFixed(3)}</td><td><span className="keyword-grade">{x.grade||"-"}</span></td><td>{x.score==null?"-":x.score.toFixed(1)}</td><td><button className="keyword-write" onClick={()=>r.push(`/blog-ai?main_keyword=${encodeURIComponent(x.keyword)}`)}>이 키워드로 글쓰기</button></td></tr>)}</tbody></table>:<p>{result?.hint||"추천 키워드가 없습니다."}</p>}</section></>}
 </div></main>}
