"use client";
import { useEffect,useMemo,useState } from "react";
import { useRouter } from "next/navigation";
import { BriefcaseBusiness, CalendarDays, ExternalLink, Link2, Loader2, LogOut, Save, ShieldCheck, Trophy } from "lucide-react";
import { getSupabaseBrowserClient } from "@/lib/supabase";

type Work={id:number;product_name:string;product_code:string|null;package_option:string|null;status:string;total_units:number;completed_units:number;guarantee_days:number;service_start_date:string|null;service_end_date:string|null;guarantee_started_at:string|null;current_rank:number|null;customer_request:Record<string,unknown>;created_at:string};
type Entry={id:number;work_order_id:number;entry_date:string;entry_type:string;title:string|null;result_url:string|null;rank_value:number|null;note:string|null;created_at:string};
const labels:Record<string,string>={assigned:"배정 완료",in_progress:"진행 중",review_requested:"검수 요청",revision:"수정 요청",completed:"완료",received:"접수"};
const productHelp:Record<string,string>={branding_blog:"완료한 블로그 포스팅 링크를 1건씩 등록합니다.",place_ranking:"상위노출 달성일에는 ‘25일 보장 시작’을 체크하고 그날 순위를 등록합니다.",place_management:"신청 다음 날부터 25일간 당일 순위를 등록합니다.",blog_ranking:"당일 노출 순위를 등록하면 보장 일수가 1일 차감됩니다."};

export default function StaffPage(){
 const router=useRouter();const[loading,setLoading]=useState(true);const[allowed,setAllowed]=useState(false);const[works,setWorks]=useState<Work[]>([]);const[entries,setEntries]=useState<Entry[]>([]);const[selected,setSelected]=useState<Work|null>(null);const[date,setDate]=useState(new Date().toISOString().slice(0,10));const[companyName,setCompanyName]=useState("");const[url,setUrl]=useState("");const[title,setTitle]=useState("");const[rank,setRank]=useState("");const[note,setNote]=useState("");const[startGuarantee,setStartGuarantee]=useState(false);const[msg,setMsg]=useState("");const[saving,setSaving]=useState(false);
 async function load(userId:string){const s=getSupabaseBrowserClient();if(!s)return;const[{data:w},{data:e}]=await Promise.all([s.from("marketing_work_orders").select("id,product_name,product_code,package_option,status,total_units,completed_units,guarantee_days,service_start_date,service_end_date,guarantee_started_at,current_rank,customer_request,created_at").eq("assigned_staff_id",userId).order("created_at",{ascending:false}),s.from("marketing_work_entries").select("id,work_order_id,entry_date,entry_type,title,result_url,rank_value,note,created_at").order("entry_date",{ascending:false}).limit(500)]);setWorks((w??[]) as Work[]);setEntries((e??[]) as Entry[]);}
 useEffect(()=>{const s=getSupabaseBrowserClient();if(!s){setLoading(false);return;}(async()=>{const{data:a}=await s.auth.getUser();if(!a.user){router.replace("/");return;}const{data:p}=await s.from("profiles").select("role,account_status").eq("id",a.user.id).single();if(!["staff","admin","super_admin"].includes(p?.role)||p?.account_status!=="active"){setLoading(false);return;}setAllowed(true);await load(a.user.id);setLoading(false);})();},[router]);
 const selectedEntries=useMemo(()=>selected?entries.filter(e=>e.work_order_id===selected.id):[],[entries,selected]);
 function open(w:Work){setSelected(w);setDate(new Date().toISOString().slice(0,10));setCompanyName(typeof w.customer_request?.company_name==="string"?String(w.customer_request.company_name):"");setUrl("");setTitle("");setRank("");setNote("");setStartGuarantee(false);setMsg("");}
 async function save(){if(!selected)return;const isPost=selected.product_code==="branding_blog";if(!companyName.trim()){setMsg("업체명을 입력해 주세요.");return;}if(isPost&&!url.trim()){setMsg("포스팅 링크를 입력해 주세요.");return;}if(!isPost&&(!rank||Number(rank)<1)){setMsg("당일 순위를 입력해 주세요.");return;}const s=getSupabaseBrowserClient();if(!s)return;setSaving(true);const{error}=await s.rpc("staff_add_work_entry",{p_work_id:selected.id,p_entry_date:date,p_entry_type:isPost?"post":"rank",p_company_name:companyName,p_title:title,p_result_url:url,p_rank_value:isPost?null:Number(rank),p_note:note,p_start_guarantee:startGuarantee});setSaving(false);if(error){setMsg(error.message);return;}const{data:a}=await s.auth.getUser();if(a.user)await load(a.user.id);setSelected(null);setMsg("작업 기록을 등록했습니다.");}
 async function logout(){const s=getSupabaseBrowserClient();await s?.auth.signOut();router.replace("/");}
 if(loading)return <main className="loading-screen"><Loader2 className="spin" size={30}/>직원 업무를 불러오는 중입니다.</main>;
 if(!allowed)return <main className="admin-denied"><ShieldCheck size={46}/><h1>직원 권한이 필요합니다.</h1><button onClick={()=>router.replace("/dashboard")}>대시보드로 돌아가기</button></main>;
 return <main className="staff-page"><header className="staff-header"><div><span><BriefcaseBusiness/></span><div><small>MOSTAD WORKSPACE</small><h1>내 배정 업무</h1></div></div><button onClick={logout}><LogOut size={17}/>로그아웃</button></header>{msg&&<div className="staff-message">{msg}</div>}<section className="staff-grid">{works.length?works.map(w=>{const progress=w.total_units?Math.min(100,Math.round(w.completed_units/w.total_units*100)):0;return <article className="staff-card staff-product-card" key={w.id}><div className="staff-card-top"><span>{w.package_option||"수동 업무"}</span><b>{labels[w.status]||w.status}</b></div><h2>{w.product_name}</h2><p>{productHelp[w.product_code||""]||"배정받은 작업 결과를 등록해 주세요."}</p><div className="staff-progress-line"><div><b>{w.completed_units}/{w.total_units||w.guarantee_days}</b><span>{w.current_rank?`현재 ${w.current_rank}위`:"진행 기록"}</span></div><i><em style={{width:`${progress}%`}}/></i></div><button onClick={()=>open(w)}>오늘 작업 등록 <ExternalLink size={16}/></button></article>}):<div className="admin-empty">현재 배정된 업무가 없습니다.</div>}</section>
 {selected&&<div className="admin-modal-backdrop"><section className="admin-member-modal work-entry-modal"><h2>{selected.product_name}</h2><p className="form-help">{productHelp[selected.product_code||""]}</p><div className="admin-form-section"><label>작업일<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>업체명<input value={companyName} onChange={e=>setCompanyName(e.target.value)} placeholder="작업한 업체명"/></label>{selected.product_code==="branding_blog"?<><label>포스팅 제목<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="포스팅 제목"/></label><label>포스팅 링크<input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://..."/></label></>:<><label>당일 순위<input value={rank} onChange={e=>setRank(e.target.value.replace(/[^0-9]/g,""))} placeholder="예: 3"/></label>{selected.product_code==="place_ranking"&&!selected.guarantee_started_at&&<label className="check-line"><input type="checkbox" checked={startGuarantee} onChange={e=>setStartGuarantee(e.target.checked)}/><span><Trophy size={16}/>상위노출 달성 · 25일 보장 시작</span></label>}<label>관련 링크<input value={url} onChange={e=>setUrl(e.target.value)} placeholder="검색 결과 또는 작업 링크(선택)"/></label></>}<label>작업 내용<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="오늘 진행한 작업과 전달사항"/></label><button className="admin-save-button" onClick={save} disabled={saving}><Save size={17}/>{saving?"저장 중...":"기록 저장"}</button><button className="staff-cancel" onClick={()=>setSelected(null)}>닫기</button></div><div className="work-history-mini"><h3><CalendarDays size={17}/>최근 기록</h3>{selectedEntries.slice(0,8).map(e=><div key={e.id}><time>{e.entry_date}</time><span>{e.entry_type==="post"?"포스팅 등록":`${e.rank_value}위`}</span>{e.result_url&&<a href={e.result_url} target="_blank" rel="noreferrer"><Link2 size={14}/></a>}</div>)}</div></section></div>}
 </main>}
