"use client";
import { useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import { BriefcaseBusiness, ExternalLink, Loader2, LogOut, Send, ShieldCheck } from "lucide-react";
import { getSupabaseBrowserClient } from "@/lib/supabase";

type Work={id:number;product_name:string;product_category:string;status:string;customer_request:Record<string,unknown>;result_title:string|null;result_url:string|null;result_note:string|null;created_at:string};
const labels:Record<string,string>={assigned:"배정 완료",in_progress:"진행 중",review_requested:"검수 요청",revision:"수정 요청",completed:"완료"};
export default function StaffPage(){const router=useRouter();const[loading,setLoading]=useState(true);const[allowed,setAllowed]=useState(false);const[works,setWorks]=useState<Work[]>([]);const[editing,setEditing]=useState<Work|null>(null);const[title,setTitle]=useState("");const[url,setUrl]=useState("");const[note,setNote]=useState("");const[msg,setMsg]=useState("");
 useEffect(()=>{const s=getSupabaseBrowserClient();if(!s){setLoading(false);return;}(async()=>{const{data:a}=await s.auth.getUser();if(!a.user){router.replace("/");return;}const{data:p}=await s.from("profiles").select("role,account_status").eq("id",a.user.id).single();if(!["staff","admin","super_admin"].includes(p?.role)||p?.account_status!=="active"){setLoading(false);return;}setAllowed(true);const{data}=await s.from("marketing_work_orders").select("id,product_name,product_category,status,customer_request,result_title,result_url,result_note,created_at").eq("assigned_staff_id",a.user.id).order("created_at",{ascending:false});setWorks((data??[]) as Work[]);setLoading(false);})();},[router]);
 function open(w:Work){setEditing(w);setTitle(w.result_title??"");setUrl(w.result_url??"");setNote(w.result_note??"");setMsg("");}
 async function submit(){if(!editing)return;const s=getSupabaseBrowserClient();if(!s)return;const{error}=await s.rpc("staff_submit_work",{p_work_id:editing.id,p_result_title:title,p_result_url:url,p_result_note:note});if(error){setMsg(error.message);return;}setWorks(x=>x.map(w=>w.id===editing.id?{...w,status:"review_requested",result_title:title,result_url:url,result_note:note}:w));setEditing(null);setMsg("검수 요청을 전송했습니다.");}
 async function logout(){const s=getSupabaseBrowserClient();await s?.auth.signOut();router.replace("/");}
 if(loading)return <main className="loading-screen"><Loader2 className="spin" size={30}/>직원 업무를 불러오는 중입니다.</main>;
 if(!allowed)return <main className="admin-denied"><ShieldCheck size={46}/><h1>직원 권한이 필요합니다.</h1><button onClick={()=>router.replace("/dashboard")}>대시보드로 돌아가기</button></main>;
 return <main className="staff-page"><header className="staff-header"><div><span><BriefcaseBusiness/></span><div><small>MOSTAD WORKSPACE</small><h1>내 배정 업무</h1></div></div><button onClick={logout}><LogOut size={17}/>로그아웃</button></header>{msg&&<div className="staff-message">{msg}</div>}<section className="staff-grid">{works.length?works.map(w=><article className="staff-card" key={w.id}><div className="staff-card-top"><span>{w.product_category}</span><b>{labels[w.status]||w.status}</b></div><h2>{w.product_name}</h2><p>접수일 {new Date(w.created_at).toLocaleDateString("ko-KR")}</p><button onClick={()=>open(w)}>작업 결과 등록 <ExternalLink size={16}/></button></article>):<div className="admin-empty">현재 배정된 업무가 없습니다.</div>}</section>{editing&&<div className="admin-modal-backdrop"><section className="admin-member-modal"><h2>{editing.product_name}</h2><p className="form-help">완료한 게시물·보고서 등의 링크와 작업 내용을 등록해 주세요.</p><div className="admin-form-section"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="결과 제목"/><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https:// 결과 링크"/><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="작업 완료 내용 및 전달사항"/><button className="admin-save-button" onClick={submit}><Send size={17}/>검수 요청</button><button className="staff-cancel" onClick={()=>setEditing(null)}>닫기</button></div></section></div>}</main>}
