create table if not exists public.keyword_analysis_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  request_id text not null,
  seed_keyword text not null,
  result jsonb not null default '{}'::jsonb,
  point_cost integer not null default 250,
  created_at timestamptz not null default now(),
  unique(user_id, request_id)
);

alter table public.keyword_analysis_history enable row level security;
drop policy if exists "keyword_history_select_own" on public.keyword_analysis_history;
create policy "keyword_history_select_own" on public.keyword_analysis_history for select using (auth.uid() = user_id);

create or replace function public.complete_keyword_analysis(
  p_user_id uuid,
  p_request_id text,
  p_seed_keyword text,
  p_result jsonb
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_cost integer := 250;
  v_balance integer;
  v_existing public.keyword_analysis_history%rowtype;
begin
  select * into v_existing from public.keyword_analysis_history
  where user_id=p_user_id and request_id=p_request_id;
  if found then
    select point_balance into v_balance from public.profiles where id=p_user_id;
    return jsonb_build_object('ok',true,'already_completed',true,'balance',coalesce(v_balance,0));
  end if;

  select point_balance into v_balance from public.profiles where id=p_user_id for update;
  if v_balance is null then raise exception '회원 포인트 정보를 찾을 수 없습니다.'; end if;
  if v_balance < v_cost then raise exception '포인트가 부족합니다.'; end if;

  v_balance := v_balance-v_cost;
  update public.profiles set point_balance=v_balance, updated_at=now() where id=p_user_id;
  insert into public.point_transactions(user_id,transaction_type,amount,balance_after,description)
  values(p_user_id,'use',-v_cost,v_balance,'검색량·키워드 분석 이용');
  insert into public.keyword_analysis_history(user_id,request_id,seed_keyword,result,point_cost)
  values(p_user_id,p_request_id,p_seed_keyword,p_result,v_cost);

  return jsonb_build_object('ok',true,'balance',v_balance,'cost',v_cost);
end;
$$;
revoke all on function public.complete_keyword_analysis(uuid,text,text,jsonb) from public;
grant execute on function public.complete_keyword_analysis(uuid,text,text,jsonb) to service_role;
